version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm run lint
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp ./dist s3://www.masivtest.io

artifacts:
  files:
    - "**/*"
discard-paths: no
base-directory: build
