version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm run lint
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp ./dist/js s3://www.masivtest.io/js --recursive --acl public-read
      - aws s3 cp ./dist/css s3://www.masivtest.io/css --recursive --acl public-read

artifacts:
  files:
    - "**/*"
discard-paths: no
base-directory: build
